### ISSUE TITLE
What does Flym-DecSync means to this project: Would be discontinued or just more options?

### ISSUE THREAD

**Issue by machiav3lli** [39aldo39/spaRSS-DecSync#18]
As you've forked Flym(a great RSS reader) and added DecSync support to it, I'm wondering if I should keep spaRSS or move to Flym (it's not a big deal thanks to DecSync), but I was thinking about adding some UI elements to the reader and now don't know if it's worth to do here, or I should better do it there(Flym-DecSync)!

**Comment by machiav3lli** [comment]
Considering that both projects (Flym & spaRSS) are inactive, maybe it would make sense to build upon other active readers like [Readrops](https://github.com/readrops/Readrops) or [NiceFeed](https://github.com/joshuacerdenia/NiceFeed)?

**Comment by 39aldo39** [comment]
Indeed, currently both spaRSS and Flym are inactive. When I added support for DecSync to Flym it was still active (see FredJul/Flym#696), but it became inactive due to a policy change of Google Play.

As I already did the work I decided to still fork it as I think the app is better than spaRSS. But yes, it would be preferable to have support for an actively maintained reader. For now I will do basic maintenance for both spaRSS and Flym to keep them working.

**Comment by machiav3lli** [comment]
Maybe it'd be possible to convience the maintainers of either Readrops or NiceFeed to include DecSync support to minimize the maintainance effort for you? If you'd like I can start the discussion there?

**Comment by 39aldo39** [comment]
Yes, it might indeed be better to implement support for a maintained app. Readrops already has an issues for it: readrops/Readrops#73. I may also implemented if I have time, although maybe I am just chasing apps that will soon be unmaintained...

**Comment by machiav3lli** [comment]
Hehe, let's not be that pessimistic. Readrops is being migrated slowly to kotlin which is a sign that the plan to maintain it for longer time is there :D

**Comment by BeatLink** [comment]
What about Feeder? https://f-droid.org/en/packages/com.nononsenseapps.feeder/

**Comment by ivysrono** [comment]
@39aldo39 Feeder may be the most active FOSS RSS reader for Android.

> What about Feeder? https://f-droid.org/en/packages/com.nononsenseapps.feeder/
